# Codecov configuration
# https://docs.codecov.com/docs/codecovyml-reference

coverage:
  # Coverage precision (number of decimal places)
  precision: 2

  # Round coverage values
  round: down

  # Range of coverage colors (red to green)
  range: "70...100"

  status:
    # Project-level coverage requirements
    project:
      default:
        target: auto
        threshold: 5%
        # Informational only - never block PRs
        informational: true

    # Patch coverage (for new code in PRs)
    patch:
      default:
        target: auto
        threshold: 5%
        # Informational only - never block PRs
        informational: true

# Ignore generated and non-essential files
ignore:
  - "target/**/*"
  - "tests/**/*"
  - "**/tests/**/*"
  - "**/*_test.rs"
  - "**/test_*.rs"
  - "benches/**/*"
  - "examples/**/*"
  - "**/*.generated.rs"

# Comment configuration for PRs
comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true
  require_base: false
  require_head: true

# Flag management for different test types
flags:
  unit:
    paths:
      - src/
    carryforward: true

# GitHub integration settings
github_checks:
  annotations: true
